### PR TITLE
Consider love potion acquired even if it was acquired in another session

### PR DESCRIPTION
**Pull request by gausie**
This still fails if you have just used the potion I guess

### CODE REVIEW

**Review by spaghetti-squash — COMMENTED** [review]
I'm not sure I understand how this solves the problem, mostly because I'm not sure what cause the problem to begin with

**Comment by Rinn** [comment]
the issue is timescast is per session, so it can be zero if you reopen mafia and you can only summon another love potion if you don't have one in inventory and don't have the effect so it can infinite loop. I had this happen a few days ago.

**Comment by gausie** [comment]
Yeah but I think my fix handles it somewhat no?

**Comment by Rinn** [comment]
yeah

**Comment by Rinn** [comment]
just hit this again today can you merge this?

**Comment by spaghetti-squash** [comment]
Ahh, yeah, sorry. In the morning i will

**Review by spaghetti-squash — APPROVED** [review]

**Pull request merged**
